"""Stable contracts shared by methods, runtime, and evaluation."""

from .candidate import Candidate, CandidateKind
from .canonical import (
    CANONICALIZATION_VERSION,
    canonical_json_bytes,
    canonical_json_document_bytes,
    canonical_jsonl_bytes,
    canonical_sha256,
    canonical_text_bytes,
    parse_json_document,
)
from .harness import (
    EditManifest,
    EditOperation,
    HarnessSnapshot,
    MemoryEntry,
    SkillEntry,
    SkillKind,
    load_learned_skill_entry,
    load_memory_entry,
    load_skill_entry,
)
from .evidence import (
    CapabilityTemplate,
    EvidenceDisposition,
    LocalBehaviorEvidence,
    ObservationScope,
    PatternNode,
    PolicyInterventionEvidence,
    ScopedObservationReceipt,
    ScopedProgramBinding,
    SignedEvidenceLedger,
    SignedEvidenceRecord,
)
from .method import (
    ExecutionReceipt,
    Method,
    PreparationRequest,
    PreparationResult,
    PreparationStatus,
    PreparedSeries,
)
from .program import Program, ProgramStep
from .observables import OBSERVABLE_FEATURES, validate_applicability
from .program_supply import PROGRAM_SUPPLY_ROUTE_FIELDS, route_program_supply_fault
from .run_context import RunDependencyBinding
from .task import (
    DeploymentConstraintSpec,
    LABEL_AVAILABILITY,
    TARGET_SEMANTICS_BY_TASK,
    TASK_TYPES,
    MetricSpec,
    TaskContext,
    TaskQualityContract,
    TaskSpec,
    anomaly_background_model_quality_contract_v1,
    anomaly_task_context_v1,
    anomaly_task_spec_v1,
    classification_global_coarse_task_quality_contract_v1,
    classification_local_event_task_quality_contract_v1,
    classification_task_context_v1,
    classification_task_spec_v1,
    deployment_constraints_v1,
    forecast_task_context_v1,
    forecast_neutral_task_quality_contract_v1,
    forecast_task_quality_contract_v1,
    forecast_task_spec_v1,
)

__all__ = [
    "Candidate",
    "CandidateKind",
    "CANONICALIZATION_VERSION",
    "CapabilityTemplate",
    "EditManifest",
    "EditOperation",
    "EvidenceDisposition",
    "DeploymentConstraintSpec",
    "ExecutionReceipt",
    "LABEL_AVAILABILITY",
    "LocalBehaviorEvidence",
    "Method",
    "HarnessSnapshot",
    "MemoryEntry",
    "OBSERVABLE_FEATURES",
    "ObservationScope",
    "PreparationRequest",
    "PreparationResult",
    "PreparationStatus",
    "PreparedSeries",
    "PatternNode",
    "PolicyInterventionEvidence",
    "Program",
    "PROGRAM_SUPPLY_ROUTE_FIELDS",
    "ProgramStep",
    "RunDependencyBinding",
    "ScopedObservationReceipt",
    "ScopedProgramBinding",
    "SkillEntry",
    "SkillKind",
    "SignedEvidenceLedger",
    "SignedEvidenceRecord",
    "TARGET_SEMANTICS_BY_TASK",
    "TASK_TYPES",
    "MetricSpec",
    "TaskSpec",
    "TaskContext",
    "TaskQualityContract",
    "anomaly_background_model_quality_contract_v1",
    "anomaly_task_context_v1",
    "anomaly_task_spec_v1",
    "classification_global_coarse_task_quality_contract_v1",
    "classification_local_event_task_quality_contract_v1",
    "classification_task_context_v1",
    "classification_task_spec_v1",
    "deployment_constraints_v1",
    "canonical_json_bytes",
    "canonical_json_document_bytes",
    "canonical_jsonl_bytes",
    "canonical_sha256",
    "canonical_text_bytes",
    "forecast_task_spec_v1",
    "forecast_task_context_v1",
    "forecast_neutral_task_quality_contract_v1",
    "forecast_task_quality_contract_v1",
    "load_learned_skill_entry",
    "load_memory_entry",
    "load_skill_entry",
    "parse_json_document",
    "route_program_supply_fault",
    "validate_applicability",
]
